#pragma once
#include "driver/gpio.h"
#define UART_DEFAULT_BAUD_RATE 115200
#define UART_RX_BUF_SIZE 1024
#define UART_TX_BUF_SIZE 0  // No TX buffer needed
#define UART_TASK_STACK_SIZE 4096
#define UART_TASK_PRIORITY 4
#define UART_TASK_CORE 0  // Core 0
#define UART_EVENT_QUEUE_SIZE 20
#define UART_MAX_DATA_SIZE 256
#define UART_READ_TIMEOUT_MS 100
#define UART_WRITE_TIMEOUT_MS 100
#define UART_DRIVER_BUFFER_SIZE 1024
#define UART_DEFAULT_TX_PIN GPIO_NUM_1
#define UART_DEFAULT_RX_PIN GPIO_NUM_3
#define UART_DEFAULT_PORT UART_NUM_0
#define UART_DEFAULT_PARITY UART_PARITY_DISABLE
#define UART_DEFAULT_STOP_BITS UART_STOP_BITS_1
#define UART_DEFAULT_FLOW_CTRL UART_HW_FLOWCTRL_DISABLE
#define UART_DEFAULT_SOURCE_CLK UART_SCLK_DEFAULT
#define UART_ISR_STACK_SIZE 2048
#define UART_ISR_PRIORITY 1
#define UART_ISR_CORE 0  // Core 0
#define UART_MAX_BAUD_RATE 921600
#define UART_MIN_BAUD_RATE 300
#define UART_DEFAULT_DATA_BITS UART_DATA_8_BITS
#define UART_MAX_DATA_BITS UART_DATA_9_BITS
#define UART_MIN_DATA_BITS UART_DATA_5_BITS
#define UART_DEFAULT_TIMEOUT_TICKS pdMS_TO_TICKS(100)